# -*- coding: utf-8 -*-
"""Real Time Gate Fraud Pattern Detection using Sliding Window (Deque).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdAWWKQi-1vh4VHnYs3m9rX7o5O6KzPx

# Real Time Gate Fraud Pattern Detection using Sliding Window (Deque)

This project simulates railway ticket scan activity and uses a deque based sliding window to detect suspicious short term behaviour. It tracks the most recent scans, calculates rolling risk signals, raises alerts, and visualises how risk changes over time. This mirrors real world fraud monitoring

Railway operators process thousands of ticket scans per hour.

Fraud or misuse often does not appear in full historical data but in short bursts of abnormal behaviour.

We need a system that:

Detects suspicious activity in real-time using only the most recent events.

Core Idea
```
Using deque to:
store last N scans (sliding window)
compute metrics on the fly
trigger alerts when patterns emerge

Building a mini real-time monitoring system (Only look at the most recent N scans)
```
Core part:
```
recent_scans = deque(maxlen=WINDOW_SIZE)
```
Means: It means:
“Always keep only the last _(e.g.8) scans”

### Data Structure

Each scan contains:

```
{
    "timestamp": int, #When did this happen?
    "amount": float, #How much did they pay? (abnormal drop=strong signal)
    "status": "allowed" or "blocked", #Did the gate accept the ticket?
    "ticket_type": "adult" / "child" / "railcard",
    "confidence": float  # model confidence (unstable confiidence = unreliable model.. Sudden drops=data drift)
}
```

```
ticket scans → model predictions
amount → feature values
status → prediction outcome
```

```
For every new scan:
Generate one scan event
Add it to the deque
If deque is full, oldest scan disappears automatically
Analyse only the recent scans in the deque
Calculate metrics
Create alerts if suspicious patterns appear
Save the result into records
At the end, turn all saved results into a pandas DataFrame
```
"""

from collections import deque
import random #fake data creation
import pandas as pd
import matplotlib.pyplot as plt

random.seed(42) #Each time I run the code, I should get the same fake data.
WINDOW_SIZE = 8
recent_scans = deque(maxlen=WINDOW_SIZE)
#The deque can only keep the most recent 8 scans. So if 10 scans arrive, the first 2 will eventually get pushed out. This is your first full sliding window.From here on, every new scan removes the oldest one automatically.for e.g. if we get (scan9) deque removes scan1.

def generate_scan(t): #t stands for timestamp
    """
    Simulate one railway ticket scan event.
    Most events are normal, but some are intentionally suspicious.
    """
    suspicious_mode = random.random() < 0.3 #gives random number between 0 and 1.. (since we are not using real data)...then we check if its less than 0.3..

    if suspicious_mode:
        amount = round(random.uniform(0.2, 2.5), 2)
        status = random.choices(["allowed", "blocked"], weights=[0.3, 0.7])[0]
        confidence = round(random.uniform(0.45, 0.95), 2)
        ticket_type = random.choice(["child", "railcard", "adult"])
    else:
        amount = round(random.uniform(5, 18), 2)
        status = random.choices(["allowed", "blocked"], weights=[0.85, 0.15])[0]
        confidence = round(random.uniform(0.75, 0.99), 2)
        ticket_type = random.choice(["adult", "adult", "railcard"])

#return the scan as a dictionary
    return {
        "timestamp": t,
        "amount": amount,
        "status": status,
        "ticket_type": ticket_type,
        "confidence": confidence
    }
# if its status is 'blocked, count 1.
def analyse_window(window):
    """
    Analyse the current sliding window and return metrics and alerts.
    """
    blocked_count = sum(1 for x in window if x["status"] == "blocked") # if its status is 'blocked, count 1.
    avg_price = sum(x["amount"] for x in window) / len(window)
    low_price_count = sum(1 for x in window if x["amount"] < 3) #Count how many scans in the window have amount less than 3.
    confidence_range = max(x["confidence"] for x in window) - min(x["confidence"] for x in window)

    risk_score = 0
    alerts = []

    if blocked_count >= 4:
        risk_score += 3 #add 3 points to risk score
        alerts.append("High blocked scan volume")


    if avg_price < 5:
        risk_score += 2
        alerts.append("Average ticket price unusually low")

    if low_price_count >= 3:
        risk_score += 2
        alerts.append("Repeated low value ticket usage")

    if confidence_range > 0.35:
        risk_score += 1
        alerts.append("Confidence instability detected")

    if blocked_count >= 4 and low_price_count >= 3:
        risk_score += 2
        alerts.append("Possible coordinated fraud pattern")

    return {
        "blocked_count": blocked_count,
        "avg_price": round(avg_price, 2),
        "low_price_count": low_price_count,
        "confidence_range": round(confidence_range, 2),
        "risk_score": risk_score,
        "alerts": alerts
    }

records = []

for t in range(1, 61): #in this project, i am only simulating 60 scan. but in real life it would be continuous (infitine)
    scan = generate_scan(t)
    recent_scans.append(scan)

    metrics = analyse_window(recent_scans)

    row = {
        "timestamp": t,
        "amount": scan["amount"],
        "status": scan["status"],
        "ticket_type": scan["ticket_type"],
        "confidence": scan["confidence"],
        "window_size": len(recent_scans),
        "blocked_count": metrics["blocked_count"],
        "avg_price": metrics["avg_price"],
        "low_price_count": metrics["low_price_count"],
        "confidence_range": metrics["confidence_range"],
        "risk_score": metrics["risk_score"],
        "alert_count": len(metrics["alerts"]),
        "alerts": ", ".join(metrics["alerts"]) if metrics["alerts"] else "No alert"
    }

    records.append(row)

df = pd.DataFrame(records)

print(df.head(10))

"""Deque is useful for real time monitoring result for;
- real time alerts without saving everything
- small window
- for speed and computing cost
- detect current behaviour. it can be used for answering 'what is happening right now?'
"""

suspicious_df = df[df["risk_score"] >= 4].copy()
print(suspicious_df[[
    "timestamp",
    "amount",
    "status",
    "confidence",
    "blocked_count",
    "avg_price",
    "low_price_count",
    "confidence_range",
    "risk_score",
    "alerts"
]].head(15))

plt.figure(figsize=(12, 5))
plt.plot(df["timestamp"], df["risk_score"], marker="o")
plt.xlabel("Time")
plt.ylabel("Risk Score")
plt.title("Rolling Risk Score Over Time")
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 5))
plt.plot(df["timestamp"], df["avg_price"], marker="o")
plt.xlabel("Time")
plt.ylabel("Average Price in Window")
plt.title("Recent Window Average Ticket Price")
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 5))
plt.plot(df["timestamp"], df["blocked_count"], marker="o")
plt.xlabel("Time")
plt.ylabel("Blocked Count")
plt.title("Blocked Scans in Sliding Window")
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 5))
plt.plot(df["timestamp"], df["confidence_range"], marker="o")
plt.xlabel("Time")
plt.ylabel("Confidence Range")
plt.title("Confidence Instability Across Recent Scans")
plt.grid(True)
plt.show()

alert_points = df[df["alert_count"] > 0]

plt.figure(figsize=(12, 5))
plt.plot(df["timestamp"], df["risk_score"], marker="o")
plt.scatter(alert_points["timestamp"], alert_points["risk_score"], s=100)
plt.xlabel("Time")
plt.ylabel("Risk Score")
plt.title("Alert Points on Risk Timeline")
plt.grid(True)
plt.show()

df[[
    "timestamp",
    "amount",
    "status",
    "ticket_type",
    "confidence",
    "blocked_count",
    "avg_price",
    "low_price_count",
    "confidence_range",
    "risk_score",
    "alerts"
]].tail(15)

"""“This is a simplified version of real-time validation logic (using simulation data)"""